"""N-cell battery-module thermal-runaway propagation model."""

from .calibration import CalibrationError, CalibrationResult, FitParameter, run_TR_calibration
from .compat import build_config, build_config_from_profile, cell_general
from .config import (
    CellConfig,
    HeaterPowerProfileConfig,
    HolderConfig,
    ModuleConfig,
    ReactionConfig,
    SolverConfig,
    ThermalNetworkConfig,
    TopologyConfig,
    TriggerConfig,
    with_heat_dissipation,
    with_heater_profile,
    with_short_energy_scale,
    with_thermal_barrier,
    without_thermal_barrier,
    validate_config,
)
from .postprocess import (
    HeatPowerSeries,
    calculate_all_interface_temperatures,
    extract_center_temperatures,
    extract_face_temperatures,
    extract_shell_surface_temperatures,
    reconstruct_heat_power,
    summarize_TR_result,
)
from .plotting import (
    nature_plot_style,
    plot_all_interface_temperatures,
    plot_concentrations,
    plot_temperatures,
    plot_thermal_network,
)
from .reactions import reaction_params
from .sensitivity import (
    SensitivityParameter,
    SimulationCase,
    SimulationSweepRun,
    export_sensitivity_csv,
    run_simulation_sweep,
    run_TR_sensitivity,
)
from .solver import SimulationError, SimulationResult, run_simulation, run_TR_model

__all__ = [
    "CalibrationResult",
    "CalibrationError",
    "CellConfig",
    "FitParameter",
    "HeaterPowerProfileConfig",
    "HolderConfig",
    "HeatPowerSeries",
    "ModuleConfig",
    "ReactionConfig",
    "SensitivityParameter",
    "SimulationCase",
    "SimulationError",
    "SimulationResult",
    "SimulationSweepRun",
    "SolverConfig",
    "ThermalNetworkConfig",
    "TopologyConfig",
    "TriggerConfig",
    "build_config",
    "build_config_from_profile",
    "calculate_all_interface_temperatures",
    "cell_general",
    "extract_center_temperatures",
    "extract_face_temperatures",
    "extract_shell_surface_temperatures",
    "export_sensitivity_csv",
    "nature_plot_style",
    "plot_all_interface_temperatures",
    "plot_concentrations",
    "plot_temperatures",
    "plot_thermal_network",
    "reaction_params",
    "reconstruct_heat_power",
    "run_TR_calibration",
    "run_TR_model",
    "run_TR_sensitivity",
    "run_simulation",
    "run_simulation_sweep",
    "summarize_TR_result",
    "validate_config",
    "with_heat_dissipation",
    "with_heater_profile",
    "with_short_energy_scale",
    "with_thermal_barrier",
    "without_thermal_barrier",
]
